# Site Settings
title: My Resume
url: 'http://delkk0.github.io'
baseurl: '/online-cv' #change it according to your repository name
about: True # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6


#Profile information
name: David Polo
tagline: R&D Electronics Engineer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: "Highly skilled electronics engineer working as R&D engineer at HP Inc. I'm like a swiss knife at my job,
I can design electronics as well as program MCUs for production or perform data analysis over a large set of data.
I'm always eager to learn new skills. Right now I'm expanding my skills towards the software side."

#sidebar links
#email: hello@webjeda.com
#phone: 012 345 6789
website: delkk0.github.io #do not add http://
linkedin: davidpolotascon
github: delkk0
#twitter: '@webjeda'
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
